- id: rebase
  name: rebase onto the default branch
  description: Rebase the current branch onto the origin default branch
  entry: ./hook.sh
  language: script
  pass_filenames: false
  stages: [commit]
